name: 每十分鐘更新月相

on:
  schedule:
    # 每十分鐘一次：*/10 * * * *
    - cron: '*/10 * * * *'
  workflow_dispatch:  # 手動觸發也可以

jobs:
  update-moon:
    runs-on: ubuntu-latest

    steps:
      - name: 取得程式碼
        uses: actions/checkout@v3

      - name: 設定 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安裝相依套件
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 執行月相腳本
        run: python scripts/get_moon_info.py

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add index.html

          # 如果有變動就 commit，沒有就跳過
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "自動更新月相網頁 @ $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          fi

          # 無條件 push（即使沒有 commit 也不會中斷）
          git push
